USE  DBDynamicWS
GO

--CONSTANTES_PARAMETRIZACION_WS
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'CONSTANTES_PARAMETRIZACION_WS')
	BEGIN 
	DROP TABLE CONSTANTES_PARAMETRIZACION_WS
END
--PUBLICADOR_WS_ESTADO_INVOC_OPER
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_ESTADO_INVOC_OPER')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_ESTADO_INVOC_OPER
END

--PUBLICADOR_WS_ESTRUCTURA_OPERACIONES
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_ESTRUCTURA_OPERACIONES')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_ESTRUCTURA_OPERACIONES
END

--PUBLICADOR_WS_PARAMETROS_TO_MAP_MANAGEBEAN
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_PARAMETROS_TO_MAP_MANAGEBEAN')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_PARAMETROS_TO_MAP_MANAGEBEAN
END

--METODOS_OPERACIONES_JSF
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'METODOS_OPERACIONES_JSF')
	BEGIN 
	DROP TABLE METODOS_OPERACIONES_JSF
END

--PARAMETROS_TO_MAP_INST_CLASS
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PARAMETROS_TO_MAP_INST_CLASS')
	BEGIN 
	DROP TABLE PARAMETROS_TO_MAP_INST_CLASS
END

--PARAMETROS_TO_MAP_METODOS
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PARAMETROS_TO_MAP_METODOS')
	BEGIN 
	DROP TABLE PARAMETROS_TO_MAP_METODOS
END


--PUBLICADOR_WS_PARAMETROS_METODOS_OPERACIONES
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_PARAMETROS_METODOS_OPERACIONES')
	BEGIN 
	--TRUNCATE TABLE PUBLICADOR_WS_EJECUCION_OPERACION_CLIENTE;
	DROP TABLE PUBLICADOR_WS_PARAMETROS_METODOS_OPERACIONES;
END


--PUBLICADOR_WS_EJECUCION_OPERACION_CLIENTE
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_EJECUCION_OPERACION_CLIENTE')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_EJECUCION_OPERACION_CLIENTE
END





--PUBLICADOR_WS_METODOS_OPERACIONES
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_METODOS_OPERACIONES')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_METODOS_OPERACIONES
END








--PUBLICADOR_WS_PARAMETROS_OPERACIONES
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_PARAMETROS_OPERACIONES')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_PARAMETROS_OPERACIONES
END

--PUBLICADOR_WS_OPERACIONES
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_OPERACIONES')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_OPERACIONES
END

--PUBLICADOR_WS_DEPENDENCIA_CLASES
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_DEPENDENCIA_CLASES')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_DEPENDENCIA_CLASES
END

--PUBLICADOR_WS_CLASES_ATRIBUTOS
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_CLASES_ATRIBUTOS')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_CLASES_ATRIBUTOS
END


--PUBLICADOR_WS_ESTRUCTURA
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_ESTRUCTURA')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_ESTRUCTURA
END

--PUBLICADOR_WS_CLASES
IF EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'PUBLICADOR_WS_CLASES')
	BEGIN 
	DROP TABLE PUBLICADOR_WS_CLASES
END


GO

